apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-test
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.10
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
