kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-fs-device
spec:
  storageClassName: local-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-class
  local:
    path: /mnt/test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node
---
apiVersion: v1
kind: Pod
metadata:
  name: myrocks-sysbench-pod
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: myrocks-sysbench
    image: master-node:5000/repo/myrocks-sysbench:latest
    command: [ "/bin/bash" ]
    args: [ "/output/exec_sysbench.sh", "/mnt/test" ]
    volumeMounts:
      - name: fs
        mountPath: /mnt/test
  volumes:
  - name: fs
    hostPath:
      path: /mnt/test
